/* Generated By:JavaCC: Do not edit this line. ParserPrologConstants.java */
package uniandes.teolen.parserJavaCC.parserProlog;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserPrologConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ARROW = 5;
  /** RegularExpression Id. */
  int PETRI = 6;
  /** RegularExpression Id. */
  int PLACES = 7;
  /** RegularExpression Id. */
  int TRANSITIONS = 8;
  /** RegularExpression Id. */
  int PETRIEND = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int ID = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int MAY = 13;
  /** RegularExpression Id. */
  int MIN = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":-\"",
    "\"PN\"",
    "\"PLACES\"",
    "\"TRANSITIONS\"",
    "\"NP\"",
    "<INT>",
    "<ID>",
    "<DIGIT>",
    "<MAY>",
    "<MIN>",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
  };

}
